import Head from "next/head";
import stylesPage from "@/styles/Page.module.scss";
import { GetServerSidePropsContext } from "next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { useTranslation } from "next-i18next";
// import styles from "@/styles/Home.module.scss";

export default function Home() {
  const { t } = useTranslation("home");
  return (
    <>
      <Head>
        <title>{`League of Forth - ${t("title")}`}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={stylesPage.main}>
        <h1>{t('title')}</h1>
      </main>
    </>
  );
}

export async function getServerSideProps({
  locale = "fr",
}: GetServerSidePropsContext) {

  return {
    props: {
      ...(await serverSideTranslations(locale, ["common", "home"])),
    },
  };
}